name: deploy

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    
    # 1. Go into GitHub Actions _work directory ($GITHUB_WORKSPACE)
    # 2. Copy all files from there to web server root (~/html)
      # -r flag to copy directories recursively
      # -u flag to skip files that have not changed
      # * means all files and directories
      # -t ~/html defines the target directory
    - name: Copy files to web server root (html directory)
      run: |
        cd $GITHUB_WORKSPACE
        cp -r -u * -t ~/html
